name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            texlive \
            texlive-luatex \
            texlive-pictures \
            texlive-publishers \
            #
      - run: make
